CREATE TABLE IF NOT EXISTS raw.ds_exposition_vacation (
	ds_id numeric(19) PRIMARY KEY,
	id numeric(19) NOT NULL,
	"timestamp" timestamp NOT NULL,
	check_price_alert numeric(10) NULL,
	final_exposure numeric(30,9) NULL,
	missing_fx_rate numeric(10) NULL,
	missing_price numeric(10) NULL,
	out_of_date_fx_rate numeric(10) NULL,
	out_of_date_price numeric(10) NULL,
	risk_measure numeric(30,9) NULL,
	status varchar(32) NULL,
	"version" numeric(10) NULL,
	risk_unit_id numeric(19) NOT NULL,
	former_exposition_vacation_id numeric(19) NULL,
	final_exposure_cl numeric(30,9) NULL,
	credit_line_rate numeric(19,4) NULL,
	global_add_on numeric(30,9) NULL,
	default_price numeric(10) NULL,
	cash_amount numeric(30,9) NULL,
	risk_amount numeric(30,9) NULL,
	end_date timestamp NULL,
	flux3_receive_date timestamp NULL,
	critical_alert_level int4 NULL DEFAULT 0,
	credit_line numeric(30,9) NULL,
	credit_line_currency_ref_id varchar(3) NULL,
	bkt_begin_date timestamp NULL,
	bkt_end_date timestamp NULL,
	bkt_ready bool NOT NULL DEFAULT false,
	bkt_ru_currency_ref_id varchar(3) NULL,
	bkt_selection_date date NULL,
	bkt_selection_criteria varchar(7) NULL,
	bkt_ru_start_time time NULL,
	bkt_ru_end_time time NULL,
	bkt_ru_timezone varchar(64) NULL,
	bkt_sent bool NULL,
	context varchar(10) NOT NULL,
	fixed_collateral numeric(30,9) NULL,
	collateral_oldest_date timestamp NULL,
	margin_cash_balance numeric(30,9) NULL,
	margin_cash_balance_date timestamp NULL,
	ru_margining_status varchar(32) NULL,
	ptf_margining_worst_status varchar(32) NULL,
	formula_equation varchar(4096) NULL,
	margin_cash_balance_currency varchar(3) NULL,
	fixed_collateral_currency varchar(3) NULL,
	insert_date date NULL,
	insert_date_time timestamp NULL
);
