-- raw.ds_portfolio definition

-- Drop table

-- DROP TABLE raw.ds_portfolio;

CREATE TABLE IF NOT EXISTS raw.ds_portfolio (
	ds_id numeric(19) NOT NULL,
	id numeric(19) NOT NULL,
	exposition_vacation_id numeric(19) NOT NULL,
	computed_var numeric(30,9) NULL,
	constitution_date timestamp NULL,
	"name" varchar(32) NULL,
	sending_date timestamp NULL,
	status varchar(32) NULL,
	"type" varchar(32) NOT NULL,
	value numeric(30,9) NULL,
	value_ok bool NULL DEFAULT false,
	var_date timestamp NULL,
	"version" numeric(10) NULL,
	global_add_on numeric(30,9) NULL,
	raw_global_add_on numeric(30,9) NULL,
	total_add_on numeric(30,9) NULL,
	holding_add_on numeric(30,9) NULL,
	total_market_value numeric(30,9) NULL,
	holding_market_value numeric(30,9) NULL,
	total_status varchar(15) NULL,
	holding_status varchar(15) NULL,
	global_fallback_ratio numeric(3,2) NULL,
	total_fallback_ratio numeric(3,2) NULL,
	holding_fallback_ratio numeric(3,2) NULL,
	global_adv_ratio numeric(3,2) NULL,
	total_adv_ratio numeric(3,2) NULL,
	holding_adv_ratio numeric(3,2) NULL,
	global_mv_ratio numeric(3,2) NULL,
	total_mv_ratio numeric(3,2) NULL,
	holding_mv_ratio numeric(3,2) NULL,
	global_rtg_ratio numeric(3,2) NULL,
	total_rtg_ratio numeric(3,2) NULL,
	holding_rtg_ratio numeric(3,2) NULL,
	log_file_id varchar(300) NULL,
	bkt_market_value numeric(30,9) NULL,
	bkt_mark_to_market numeric(30,9) NULL,
	margining_mr numeric(30,9) NULL,
	margining_im numeric(30,9) NULL,
	margining_vm numeric(30,9) NULL,
	margining_lcrm numeric(30,9) NULL,
	margining_wwr numeric(30,9) NULL,
	algorithm varchar(32) NOT NULL,
	computation_currency_ref_id varchar(3) NULL,
	ru_currency_ref_id varchar(3) NULL,
	conversion_rate numeric(19,8) NULL,
	exchange_rate_date date NULL,
	margining_mr_original numeric(30,9) NULL,
	margining_status varchar(32) NULL,
	context varchar(10) NOT NULL,
	fallback_portfolio_id numeric NULL,
	portfolio_excluded bool NOT NULL,
	insert_date date NULL,
	insert_date_time timestamp NULL,
	lcn varchar(12) NULL,
	df_multiplier numeric(3,2) NULL
);
