-- raw.ds_risk_unit definition

-- Drop table

-- DROP TABLE raw.ds_risk_unit;

CREATE TABLE IF NOT EXISTS raw.ds_risk_unit (
	ds_id numeric(19) NOT NULL,
	id numeric(19) NOT NULL,
	access_code varchar(10) NOT NULL,
	credit_line numeric(10) NULL,
	financing bool NULL DEFAULT false,
	identification varchar(32) NOT NULL,
	last_var_computation_date timestamp NULL,
	"name" varchar(32) NOT NULL,
	id_origin numeric(19) NULL,
	setup varchar(32) NOT NULL,
	var_computation_period numeric(10) NULL,
	"version" numeric(10) NULL,
	client_entity_id numeric(19) NOT NULL,
	mr_currency_ref_id varchar(3) NULL,
	reference_currency_ref_id varchar(3) NOT NULL,
	last_exposition_vacation_id numeric(19) NULL,
	var_parameters_id numeric(19) NOT NULL,
	branch varchar(3) NULL,
	crds_id varchar(12) NULL,
	credit_line_currency_ref_id varchar(3) NULL,
	credit_line_last_update timestamp NULL,
	lowest_final_exposure_cl numeric(30,9) NULL,
	lowest_fe_vacation_id numeric(19) NULL,
	btf bool NULL DEFAULT false,
	funding_credit_line numeric(30,9) NULL DEFAULT '-1'::integer,
	funding_cl_last_update timestamp NULL,
	btf_haircut numeric(30,9) NULL,
	btf_cash_request_matching bool NOT NULL DEFAULT false,
	description varchar(100) NULL,
	alert_group_id numeric(19) NULL,
	otc_min_settlement_date numeric(5) NULL,
	otc_max_settlement_date numeric(5) NULL,
	computation_mode_code varchar(32) NOT NULL DEFAULT 'FREQUENCY'::character varying,
	computation_min_bound time NULL,
	computation_max_bound time NULL,
	flux2_send_date timestamp NULL,
	btf_threshold numeric(21) NOT NULL DEFAULT 0,
	critical_alert_level numeric(1) NULL,
	alert_level int4 NULL,
	unique_id varchar(64) NULL,
	bkt_start_time time NULL,
	bkt_end_time time NULL,
	bkt_timezone varchar(64) NULL,
	bkt_last_selection date NULL,
	gcm bool NOT NULL DEFAULT false,
	simulation bool NOT NULL,
	ptf_sim_exec_id numeric NULL,
	margining_enabled bool NOT NULL,
	margining_config_id numeric(19) NULL,
	margining_formula_type varchar(32) NULL,
	minimum_deposit numeric(30,9) NULL,
	insert_date date NULL,
	insert_date_time timestamp NULL,
	dual_mode bool NULL,
	bic_code varchar(12) NULL
);
